version: '3'

services:

  magasin-mysql:
    image: mysql:latest
    container_name: mysql-magasin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MagasinDb
      - MYSQL_USER=magasin-user
      - MYSQL_PASSWORD=password
    ports:
      - 33006:3306
    #service 2: definition of phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - 8082:80
    restart: always
        
    depends_on:
      - magasin-mysql
    environment:
      SPRING_DATASOURCE_USERNAME: magasin-user
      SPRING_DATASOURCE_PASSWORD: password
  magasin-main:
    image: magasin-image
    container_name: magasin
    restart: on-failure
    depends_on:
      - magasin-mysql
    ports:
      - 8888:8080
    environment:
      - DATABASE_HOST=magasin-mysql
      - DATABASE_USER=magasin-user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=MagasinDb
      - DATABASE_PORT=3306
