---
devservers:
  hosts:
    vmserverone:
      ansible_host: 192.168.1.101
    vmservertwo:
      ansible_host: 192.168.1.102
  vars:
    ansible_become_pass: vmserver
    ansible_connection: ssh
    ansible_password: vmserver
    ansible_user: vmserver
